### ISSUE TITLE
Recovery Service missed value in  response of list method

### ISSUE THREAD

**Issue by 00Kai0** [Azure/azure-rest-api-specs#11610]
I got a different response from swagger in Recovery Services:
my response:
```
- request:
    body: null
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - azsdk-python-mgmt-recoveryservices/1.0.0b1 Python/3.6.9 (Linux-4.9.184-linuxkit-x86_64-with-Ubuntu-18.04-bionic)
    method: GET
    uri: https://management.azure.com/Subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test_mgmt_recoveryservices_test_retrieve_vault_usages5812162c/providers/Microsoft.RecoveryServices/vaults/PythonSDKTestResource/replicationUsages?api-version=2016-06-01
  response:
    body:
      string: '{"monitoringSummary":{"unHealthyVmCount":0,"unHealthyProviderCount":0,"eventsCount":0,"deprecatedProviderCount":0,"supportedProviderCount":0,"unsupportedProviderCount":0},"jobsSummary":{"failedJobs":0,"suspendedJobs":0,"inProgressJobs":0},"protectedItemsSummary":{"irInProgressProtectedItemsCount":0,"testFailoverInProgressProtectedItemsCount":0,"testFailoverWaitingProtectedItemsCount":0,"failoverInProgressProtectedItemsCount":0,"failedOverProtectedItemsCount":0,"changePitInProgressProtectedItemsCount":0,"failoverCommitInProgressProtectedItemsCount":0,"failoverCommittedProtectedItemsCount":0,"testFailoverApplicableProtectedItemsCount":0,"replicatingProtectedItemsCount":0,"hyperVToAzureProtectedItemsCount":0,"vmmToAzureProtectedItemsCount":0,"vmwareToAzureProtectedItemsCount":0,"azureToAzureProtectedItemsCount":0},"storageAccountsCountSummary":{"hyperVToAzureTotalStorageAccountsCount":0,"hyperVToAzureLogStorageAccountsCount":0,"hyperVToAzureRecoveryStorageAccountsCount":0,"vmwareToAzureStorageAccountsCount":0,"vmwareToAzureLogStorageAccountsCount":0,"vmwareToAzureRecoveryStorageAccountsCount":0,"azureToAzureRecoveryStorageAccountsCount":0,"azureToAzureStagingStorageAccountsCount":0},"protectedItemCount":0,"registeredServersCount":0,"recoveryPlanCount":0}'
    headers:
      cache-control:
      - no-cache
      content-length:
      - '1271'
      content-type:
      - application/json
      date:
      - Tue, 10 Nov 2020 06:01:34 GMT
      expires:
      - '-1'
      pragma:
      - no-cache
      server:
      - Microsoft-IIS/10.0
      - Kestrel
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      transfer-encoding:
      - chunked
      vary:
      - Accept-Encoding
      x-content-type-options:
      - nosniff
    status:
      code: 200
      message: OK
```

in swagger:
```
{
  "value": [
    {
      "monitoringSummary": {
        "unHealthyVmCount": 0,
        "unHealthyProviderCount": 0,
        "eventsCount": 0,
        "deprecatedProviderCount": 0,
        "supportedProviderCount": 0,
        "unsupportedProviderCount": 0
      },
      "jobsSummary": {
        "failedJobs": 0,
        "suspendedJobs": 0,
        "inProgressJobs": 0
      },
      "protectedItemCount": 2,
      "registeredServersCount": 2,
      "recoveryPlanCount": 1
    }
  ]
}
```
