### ISSUE TITLE
duplicate Operations_List in applicationinsights package-2021-11-01

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-rest-api-specs#17215]
applicationinsights added package-2021-11-01 in commit c03e6d67c7a67d4a598305ff484e7b40a2f264e7:

https://github.com/Azure/azure-rest-api-specs/blob/322d0edbc46e10b04a56f3279cecaa8fe4d3b69b/specification/applicationinsights/resource-manager/readme.md?plain=1#L225-L248

The problem is explained in the Azure SDK for Go workaround:

https://github.com/Azure/azure-rest-api-specs/blob/322d0edbc46e10b04a56f3279cecaa8fe4d3b69b/specification/applicationinsights/resource-manager/readme.go.md?plain=1#L12-L23

This does not work for Azure SDK for Rust or third party code generators. There should not be a duplicate operation definition.

```
directive:
# Duplicate OperationId Operations_List is detected in Microsoft.Insights/stable/2015-05-01/aiOperations_API.json and Microsoft.Insights/preview/2020-06-02-preview/livetoken_API.json
  from: aiOperations_API.json
  where: $.paths
  transform: delete $["/providers/Microsoft.Insights/operations"]
```

~A suggested solution would be to copy Microsoft.Insights/stable/2015-05-01/aiOperations_API.json to a new API folder and remove Operations_List.~
