### ISSUE TITLE
Pageable LROs should be defined with `x-ms-pageable`

### ISSUE THREAD

**Issue by heaths** [Azure/azure-rest-api-specs#20875]
There's a few LROs that are meant to return pageable results once complete - the original URI - and should be defined as such per https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-pageable.

These include, but may not be limited to:

* QuestionAnsweringProjects_UpdateQnas
* QuestionAnsweringProjects_UpdateSources

For now in the SDK, we are using transforms but these changes should be in the swagger initially. For reference:
```yaml
- where-operation: QuestionAnsweringProjects_UpdateQnas
  transform: |
    $["x-ms-pageable"] = {
      "nextLinkName": "nextLink",
      "itemName": "value"
    };

- where-operation: QuestionAnsweringProjects_UpdateSources
  transform: |
    $["x-ms-pageable"] = {
      "nextLinkName": "nextLink",
      "itemName": "value"
    };
```
