### ISSUE TITLE
[TypeSpec Requirement] Add suppression mechanism

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#27348]
Design for new suppression mechanism for all new checks in repo `azure-rest-api-specs` going forward:

1. Starting from the file/folder you are analyzing, walk up the directory tree until you find a file named `suppressions.yaml`.
   1. If none found, then nothing is suppressed.
   2. The suppressions file closest to the file being analyzed wins.  There is no concept of merging suppressions from files in nested parent directories.
2. Simple YAML schema, something like:
```yaml
- tool: TypeSpecRequirement
  path: data-plane/*.json
  reason: Brownfield service not ready to migrate
  
- tool: TypeSpecValidation
  code: FolderStructure
  reason: Must use non-standard folder structure to avoid breaking changes
```
3. Tools should print a warning message for any rules suppressed (don't silently ignore suppressed rules)
