### ISSUE TITLE
[suppressions.yaml] Add "paths" property as sibling of "path"

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#29000]
## Summary

Add `paths` array to simplify multi-version suppressions:

```
- tool: TypeSpecRequirement
  paths:
  - data-plane/Azure.Contoso.WidgetManager/preview/2022-11-01-preview/**/*.json
  - data-plane/Azure.Contoso.WidgetManager/preview/2023-11-01-preview/**/*.json
  - data-plane/Azure.Contoso.WidgetManager/preview/2024-11-01-preview/**/*.json
  reason: Same reason for all versions
```

This is equivalent and would also be an allowed alternative:

```
- tool: TypeSpecRequirement
  path: data-plane/Azure.Contoso.WidgetManager/preview/2022-11-01-preview/**/*.json
  reason: Same reason for all versions

- tool: TypeSpecRequirement
  path: data-plane/Azure.Contoso.WidgetManager/preview/2023-11-01-preview/**/*.json
  reason: Same reason for all versions

- tool: TypeSpecRequirement
  path: data-plane/Azure.Contoso.WidgetManager/preview/2024-11-01-preview/**/*.json
  reason: Same reason for all versions
```

## Open Issues
- How to require **either** `path` or `paths` in `zod` validation library?
- What if both `path` and `paths` specified?
  - Add path to array
  - Add path to array AND warn
  - Error
