### ISSUE TITLE
[TypeSpecValidation/LinterRuleset] Improve error message when tspconfig contains old ruleset

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#29359]
Current:

```
Rule LinterRuleset failed
tspconfig.yaml references the following ruleset which is deprecated:

linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"

It should be replaced with the following:

linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"tspconfig.yaml must define the following property:

linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
```

Problems:
* Second error is redundant with first
* Missing newline between two error messages

Example:

https://github.com/Azure/azure-rest-api-specs-pr/pull/18316/checks?check_run_id=25870582083
