### ISSUE TITLE
[BUG] during vm creation, using image version "latest" does not actually pull latest version because it does not sort numerically but lexicographically

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-rest-api-specs#30142]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2024-07-01/virtualMachine.json

### API Spec version

2024-07-01

### Describe the bug

Hi,
so using "latest" when selecting a marketplace image like for example:
```
    publisher: RedHat
    offer: RHEL
    sku: 8-lvm-gen2
    version: latest
```

does not work because the sorting used is lexicographically instead of numerically

Latest version at this moment would be `8.10.2024070513` but it picks `8.9.2024022012`

### Expected behavior

Use newest version (numerical) RHEL 8.10

### Actual behavior

Use "newest" version (lexicographically) RHEL 8.9

### Reproduction Steps

Use ansible to create a VM:
```
- name: Create VM in Azure
  azure.azcollection.azure_rm_virtualmachine:
    subscription_id: "{{ subscription_id }}"
    name: "testvm"
    resource_group: "{{ resource_group_name }}"
    vm_size: "{{ vm_size }}"
    network_interface_names: "{{ nic_id }}"
    os_disk_name: "testvm-disk1-os"
    created_nsg: false
    os_type: Linux
    image:
      publisher: RedHat
      offer: RHEL
      sku: 8-lvm-gen2
      version: latest
    ssh_password_enabled: false
    admin_username: username
    ssh_public_keys:
      - path: /home/username/.ssh/authorized_keys
        key_data: "{{ ssh_public_key }}"
    managed_disk_type: Premium_LRS
    boot_diagnostics:
      enabled: true
      type: managed
    security_profile:
      encryption_at_host: true
      security_type: TrustedLaunch
      uefi_settings:
        secure_boot_enabled: true
        v_tpm_enabled: true
    state: present
    started: true
    vm_identity:
      type: SystemAssigned
```
