### ISSUE TITLE
[Swagger LintDiff] Check fails even though it reports 0 errors

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#31064]
Why is LintDiff failing, even though it reported 0 errors?

https://github.com/Azure/azure-rest-api-specs/pull/30970/checks?check_run_id=31636591011

**Comment by mikeharder** [comment]
The root cause was the readme.md in `main` had invalid YAML, where the default tag was parsed as a `timestamp` instead of a `string`.

This behavior is in YAML itself, not our code.  YAML has types for strings and timestamps, and an unquoted string is parsed as a timestamp if possible.

```yaml
value-parsed-as-string-1: "2024-05-01"
value-parsed-as-string-2: foo2024-05-01
value-parsed-as-timestamp: 2024-05-01
```
