### ISSUE TITLE
[BUG] [JS SDK]

### ISSUE THREAD

**Issue by maorleger** [Azure/azure-rest-api-specs#31610]
### API Spec link

https://github.com/Azure/azure-rest-api-specs/blob/2822c0909ef7e9aa52c2921e5f0fdb0027ee3f82/specification/keyvault/Security.KeyVault.Administration/tspconfig.yaml

### API Spec version

N/A

### Describe the bug

When `generateMetadata` is false, JS SDK CI validation will fail due to automation deleting all files when generating JS SDK (including package.json)

Example typespec-ts configuration:

```yaml
  "@azure-tools/typespec-ts":
    package-dir: "keyvault-admin"
    generateMetadata: false
    generateTest: false
    experimentalExtensibleEnums: true
    isModularLibrary: true
    packageDetails:
      name: "@azure/keyvault-admin"
      description: "Azure Key Vault Administration"
    flavor: azure
```

### Expected behavior

JS SDK code generation should not be a destructive operation for files it does not regenerate

### Actual behavior

Adding the above typespec-ts entry to the yaml causes CI to start failing with (what I think is): [automation_generate.sh] [ERROR]: Failed to generate package due to Error: Could not read package.json: Error: ENOENT: no such file or directory, open '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/keyvault/keyvault-admin/package.json'

### Reproduction Steps

(this tspconfig.yaml has not been merged yet, depending on whether its merged the steps may change)

1. checkout commit sha [2822c0909ef7e9aa52c2921e5f0fdb0027ee3f82](https://github.com/Azure/azure-rest-api-specs/blob/2822c0909ef7e9aa52c2921e5f0fdb0027ee3f82/specification/keyvault/Security.KeyVault.Administration/tspconfig.yaml)
2. Create a pull request
