### ISSUE TITLE
[suppressions] Allow suppressing individual rules and sub-rules within a tool

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#31865]
Add properties "rules" and "sub-rules", which is a list of strings that are regexes matched against rule and sub-rule names.

```js
export interface Suppression {
  tool: string;
  rules?: string[];
  subRules?: string[];
  paths: string[];
  reason: string;
}
```

Example:

```yaml
- tool: TypeSpecValidation
  path: specification/monitor/**/tspconfig.yaml
  rules: [TspConfigValidation]
  sub-rules: 
    - tspconfig-*-contains-package-name
    - tspconfig-js-*
```
