### ISSUE TITLE
[EngSys] Ensure all workflow trigger path folders end with "**"

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-rest-api-specs#33062]
If a workflow sets a trigger path folder like this, it only includes file in the first level dir.

```yaml
on:
  pull_request:
    paths:
    - ".github"
    - "eng/tools"
```

To include all files under the folder recursively, it must end with "**":

```yaml
on:
  pull_request:
    paths:
    - ".github/**"
    - "eng/tools/**"
```
