### ISSUE TITLE
[BUG] Azure OpenAI API chat/completions/response/object

### ISSUE THREAD

**Issue by adubovik** [Azure/azure-rest-api-specs#33155]
### API Spec link

github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2025-02-01-preview/inference.yaml#L4286-L4293

### API Spec version

2025-02-01-preview

### Describe the bug

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2025-02-01-preview/inference.yaml#L4286-L4293

```yaml
        object:
          type: string
          description: The object type, which is always `chat.completion.chunk`.
          enum: [chat.completion.chunk]
          required:
            - prompt_tokens
            - completion_tokens
            - total_tokens
```

Unexpected `required` field content for the `object` **string** field. 

### Expected behavior

`required` field is redundant and could be removed

### Actual behavior

`required` is present and confusing since the `object` field is of string type

### Reproduction Steps

Observe https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2025-02-01-preview/inference.yaml#L4286-L4293
