### ISSUE TITLE
[DocDB] Is checkName valid?

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-rest-api-specs#689]
Hi @dmakwana

Testing `chackNameExists` leads an error in Python:
```python
msrestazure.azure_exceptions.CloudError: 401 Client Error: Unauthorized for url: https://management.azure.com/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX/providers/Microsoft.DocumentDB/databaseAccountNames/mypydocdbe7ce0d93?api-version=2015-04-08
```

Could you take a look at the Swagger file and confirm this seems to be valid? If yes, have you an idea of why it fails?

Thanks,

**Comment by dmakwana** [comment]
I looked at the Swagger file and it seems to be valid. Which subscription ID are you testing with? Make sure the calls you make are authorized for that subscription ID.

**Comment by lmazuel** [comment]
@dmakwana I was waiting more testing before answering. I was able to do create/list/list_keys/regenerate, etc. with this subscription but still the same error on "checkName". So I guess my subscription is OK (I don't think I can be able to create an account, but not check a name no?)

**Comment by lmazuel** [comment]
HTTP query:
```yaml
interactions:
- request:
    body: null
    headers:
      Accept: [application/json]
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      Content-Type: [application/json; charset=utf-8]
      User-Agent: [python/3.5.1 (Windows-10-10.0.14393-SP0) requests/2.11.1 msrest/0.4.4
          msrest_azure/0.4.3 documentdb/0.1.0 Azure-SDK-For-Python]
      accept-language: [en-US]
      x-ms-client-request-id: [028bc236-a550-11e6-861c-ecb1d756380e]
    method: HEAD
    uri: https:/management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.DocumentDB/databaseAccountNames/mypyddbtestf5d40e06?api-version=2015-04-08
  response:
    body: {string: ''}
    headers:
      Cache-Control: [no-cache]
      Connection: [close]
      Content-Length: ['0']
      Content-Type: [application/json]
      Date: ['Tue, 08 Nov 2016 01:09:33 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server: [Microsoft-HTTPAPI/2.0]
      Strict-Transport-Security: [max-age=31536000; includeSubDomains]
      x-ms-activity-id: [73139e54-abe6-4c14-a3b0-fac9bd0066db]
      x-ms-correlation-request-id: [d39fa77b-5e3e-4dc3-b0ed-133cdff6219f]
      x-ms-ratelimit-remaining-subscription-reads: ['14972']
      x-ms-request-id: [d39fa77b-5e3e-4dc3-b0ed-133cdff6219f]
      x-ms-routing-request-id: ['NORTHCENTRALUS:20161108T010934Z:d39fa77b-5e3e-4dc3-b0ed-133cdff6219f']
    status: {code: 401, message: Unauthorized}
version: 1
```

(subscription replaced for security)
