### ISSUE TITLE
Proposal: Generation reproducibility, serviceability, and configuration locality

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-rest-api-specs#8955]
Goals:

1. Checking out repository and running code generation produces the same result independently from outside factors (like autorest version, state of other repos, state of developers machine, etc.), without requiring developers to install any particular version of Autorest, figure out what revision of spec repo was used etc.

2. All projects are consistently kept up-to-date with the new generator version. Situation where re-running the generator on existing project and breaks it or fails should never be able to happen.

3. Configuration for generated code is located next to and versioned with the code itself.

This both improves servicing scenarios, consistency and allows for easier iteration when libraries are first onboarderd.

There are usually 3 inputs to code generation:
1. Autorest + Plugins
2. Language configuration file
3. Swagger spec

To guarantee a reproducible code generation all three of these things have to version with the repo.

Proposal:

1. Make Autorest version tied to the language repo: entire repository uses one version of autorest and autorest language plugin at a time. The version is checked in as part of the repo and global autorest installation is **never** used. When autorest version is updated all generated code is regenerated to guarantee that there are no regressions.

Additional side effect is that devs never need to manager their installations of autorest and everyone is on the same version.

We should also have a consistent way to invoke generation across the repos that take repo specific autorest version into account.

2. Main swagger README.md stay in `azure-rest-api-specs` repo. Specific commits of swagger spec is referenced from the language repo, instead of the latest head. When swagger spec is updated the automation updates the version referenced and reruns the automation.

3. Move language specific configuration (`readme.csharp.md`) to language repos and rename to `autorest.md`.

I haven't found a convincing argument to keep language configuration files centralized when SDKs are already merged into single monorepo, and having it localized to individual repos allows for simplified developer workflows when libraries are onboarded (easy to add transformations to workaround bugs etc.) and gives a convenient way of implementing the previous step by having azure-rest-api-specs README.md reference including the commit hash in `autorest.md`.

I've picked `autorest.md` as the name because of the Track 2 requirements for README files.

# Example:

**azure-sdk-for-net/sdk/formrecognizer/Azure.AI.FormRecognizer/src/autorest.md**

Would contain something like:
``` yaml
require: https://github.com/Azure/azure-rest-api-specs/blob/4de63a0387443e9d08213abe4bc32787a5156483/specification/cognitiveservices/data-plane/FormRecognizer/readme.md

csharp:
  azure-arm: true
  license-header: MICROSOFT_MIT_NO_VERSION
  payload-flattening-threshold: 2
```

**Comment by pakrym** [comment]
cc @weshaggard @lmazuel

**Comment by pakrym** [comment]
cc @johanste

**Comment by weshaggard** [comment]
@NullMDR can you give us some idea of how much work would be involved to enable this split of configuration between the language and spec repo?

**Comment by NullMDR** [comment]
@weshaggard I need some time to investigate the problems we have and the impact of these changes. @fearthecowboy @pakrym is the `require:` mentioned in the comment currently a supported feature in autorest?

```yaml
require: https://github.com/Azure/azure-rest-api-specs/blob/4de63a0387443e9d08213abe4bc32787a5156483/specification/cognitiveservices/data-plane/FormRecognizer/readme.md

csharp:
  azure-arm: true
  license-header: MICROSOFT_MIT_NO_VERSION
  payload-flattening-threshold: 2
```
